name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gfortran gcc build-essential
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest
    
    - name: Build C/Fortran library
      run: |
        make
    
    - name: Run tests
      run: |
        pytest tests/ -v
    
    - name: Run standalone accuracy tests
      run: |
        python test_exact_equality.py
        python verify_floating_point_accuracy.py
    
    - name: Run benchmark scripts
      run: |
        python compare_scipy_vs_dfitpack_direct.py